```{r}

library(knitr)
library(igraph)
library("RColorBrewer")
library(ggplot2)
opts_chunk$set(fig.width=9, fig.height=9)
opts_chunk$set(dev=c('png','postscript'))



```


```{r}
#thies <- read.nexus("sum_ALL.target.2.nexus")
cols <- scale_color_gradient2(low="blue",mid="black",high="red")


all <- read.table("Thies_ALL.green.txt",header=T)
ggplot(all,aes(x=date,y=distance,label=tip,color=residual)) + geom_text() + geom_smooth(method="lm",se=F,fullrange=T) + cols + xlim(2000,2015) + ylim(0,max(all$distance))


snp <- read.table("Thies_SNP.green.txt",header=T)
ggplot(snp,aes(x=date,y=distance,label=tip,color=residual)) + geom_text() + geom_smooth(method="lm",se=F,fullrange=T) + cols + xlim(2000,2015) + ylim(0,max(snp$distance))

indel <- read.table("Thies_INDEL.green.txt",header=T)
ggplot(indel,aes(x=date,y=distance,label=tip,color=residual)) + geom_text() + geom_smooth(method="lm",se=F,fullrange=T) + cols+ xlim(2000,2015) + ylim(0,max(indel$distance))


#correlation indices
c(cor(all$distance,all$date),
  cor(snp$distance,snp$date),
  cor(indel$distance,indel$date))

#without 2011 clade
d = !all$tip %in% c("Th134.11","Th106.11","Th117.11")
c(cor(all$distance[d],all$date[d]),
  cor(snp$distance[d],snp$date[d]),
  cor(indel$distance[d],indel$date[d]))
#2011 clade and root only
d = all$tip %in% c("Th086.07","Th134.11","Th106.11","Th117.11")
c(cor(all$distance[d],all$date[d]),
  cor(snp$distance[d],snp$date[d]),
  cor(indel$distance[d],indel$date[d]))

```


```{r}
ggplot(all,aes(x=date,y=distance,label=tip)) + geom_point() + geom_text() + geom_smooth(method="lm",se=F,fullrange=T,colour="black",linetype=2) + xlim(2000,2015)
#ggplot(all,aes(x=date,y=distance,label=tip)) + geom_text() + geom_smooth(data=subset(all,date!=2007),method="lm",se=F) + xlim(2006,2013) #+ ylim(0,max(indel$distance))


#ggplot(snp,aes(x=date,y=distance,label=tip)) + geom_text() + geom_smooth(method="lm",se=F) + xlim(2006,2013) + ylim(0,max(snp$distance))

#ggplot(indel,aes(x=date,y=distance,label=tip)) + geom_text() + geom_smooth(method="lm",se=F) + xlim(2006,2013) #+ ylim(0,max(indel$distance))

#ggplot(indel,aes(x=date,y=distance,label=tip)) + geom_text() + geom_smooth(data=subset(indel,date!=2007),method="lm",se=F) + xlim(2006,2013) #+ ylim(0,max(indel$distance))



```
