library(ggplot2)
library(knitr)
library(reshape2)
library(hexbin)
```{r setup}
opts_chunk$set(fig.width=12, fig.height=7, fig.path="figure/chrs-")

``` 

```{r}
calcols <- c("chr","st","en","NV","LDfails","LDpass","RSfails","RSpass","df","dn","Dpass","multipass")
callable1k_disco <- read.table("qDD2vr3D7.callable.blocks1k.tab.txt",stringsAsFactors = T,sep='\t',header=F,col.names = calcols)
callable1k_haplo <- read.table("fakeNGS_haplo_qDD2r3D7_rl100.callable.1k.txt",stringsAsFactors = T,sep='\t',header=F,col.names = calcols)

callable1k_disco <- callable1k_disco[,c(1,2,3,12)]
callable1k_haplo <- callable1k_haplo[,c(1,2,3,12)]
colnames(callable1k_disco)[[4]] <- "disco"
colnames(callable1k_haplo)[[4]] <- "haplo"
callable1k_haplo$haplo = callable1k_haplo$haplo=="True"
callable1k_disco$disco = callable1k_disco$disco=="True"

callable1k<-merge(callable1k_disco,callable1k_haplo)
# callable1k$accessible <- NULL
# callable1k[callable1k$disco=="True" & callable1k$haplo=="False","accessible"] <- "DISCOVAR only"
# callable1k[callable1k$disco=="False" & callable1k$haplo=="True","accessible"] <- "haplo only"
# callable1k[callable1k$disco=="False" & callable1k$haplo=="False","accessible"] <- "inacessible"

levels(callable1k$chr) <- c("MIT","01","02","03","04","05","06","07","08","09","10","11","12","13","14","API")
callable1k <- subset(callable1k,!chr %in% c("MIT","API"))
```



```{r}
calcols <- c("chr","st","en","NV","LDfails","LDpass","RSfails","RSpass","df","dn","Dpass","multipass")
callable5k_disco <- read.table("qDD2vr3D7.callable.blocks5k.tab.txt",stringsAsFactors = T,sep='\t',header=F,col.names = calcols)
callable5k_haplo <- read.table("fakeNGS_haplo_qDD2r3D7_rl100.callable.5k.txt",stringsAsFactors = T,sep='\t',header=F,col.names = calcols)

callable5k_disco <- callable5k_disco[,c(1,2,3,12)]
callable5k_haplo <- callable5k_haplo[,c(1,2,3,12)]

colnames(callable5k_disco)[[4]] <- "disco"
colnames(callable5k_haplo)[[4]] <- "haplo"
callable5k_haplo$haplo = callable5k_haplo$haplo=="True"
callable5k_disco$disco = callable5k_disco$disco=="True"

callable5k<-merge(callable5k_disco,callable5k_haplo)
# callable5k$accessible <- NULL
# callable5k[callable5k$disco=="True" & callable5k$haplo=="False","accessible"] <- "DISCOVAR only"
# callable5k[callable5k$disco=="False" & callable5k$haplo=="True","accessible"] <- "haplo only"
# callable5k[callable5k$disco=="False" & callable5k$haplo=="False","accessible"] <- "inacessible"

levels(callable5k$chr) <- c("MIT","01","02","03","04","05","06","07","08","09","10","11","12","13","14","API")
callable5k <- subset(callable5k,!chr %in% c("MIT","API"))
```

```{r}
telos <- readLines("List.subtelomeres.3D7.regions.txt")
telos <- t(as.data.frame(strsplit(telos,split = ':')))
telos <- as.data.frame(cbind(telos[,1],t(as.data.frame(strsplit(telos[,2],split = '-')))))
colnames(telos) <- c("chr","st","en")
telos$st <- as.numeric(as.character(telos$st))
telos$en <- as.numeric(as.character(telos$en))
levels(telos$chr) <- c("01","02","03","04","05","06","07","08","09","10","11","12","13","14")

telos <- merge(subset(telos,st < 1000),subset(telos,st > 1000),by="chr")
colnames(telos) <- c("chr","stL","enL","stR","enR")


#callable5k$chr <- as.character(callable5k$chr)
callable5k$telo=F
tmp <- merge(callable5k,telos,by="chr",all.x=T)

tmp[is.na(tmp$stL),c("stL","enL","stR","enR")] <- -1
tmp$telo[tmp$en < tmp$enL] = T # "L"
tmp$telo[tmp$st > tmp$stR] = T # "R"
callable5k <- tmp[,colnames(callable5k)]
rm(tmp)
```

```{r}
callable5k$accessible=F
callable5k$accessible[callable5k$disco & !callable5k$haplo] <- "DISCOVAR"
callable5k$accessible[callable5k$haplo & !callable5k$disco] <- "GATK"
callable5k$accessible[callable5k$haplo & callable5k$disco] <- NA

callable5k$accessible[!callable5k$disco & !callable5k$haplo] <- "INACCESSIBLE"

callable5k$accessible[!callable5k$disco & !callable5k$haplo & callable5k$telo] <- "INACCESSIBLE (TELOMERE)"

callable5k$accessible <- factor(callable5k$accessible,levels=c("DISCOVAR",
                                                               "GATK",
                                                               "INACCESSIBLE",
                                                               "INACCESSIBLE (TELOMERE)"
                                                               ))
```

```{r}
chrlen <- as.data.frame(aggregate(callable5k$en,list(callable5k$chr),FUN=max))
chrlen$st=1
colnames(chrlen) <- c("chr","st","en")
```


```{r}

blank_theme <-   theme(axis.line.y=element_blank(), axis.ticks.y=element_blank(),axis.text.y=element_blank(),
        panel.background=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        legend.position="bottom")
ggplot(callable5k,aes(xmin=st,xmax=en,ymin=0,ymax=1)) + 
  ggtitle(paste("callable regions (5kb windows)")) +
  geom_rect(aes(fill=accessible)) + scale_fill_manual(values=c("blue","orange","grey","#888888"))+
  geom_rect(data=chrlen,fill=NA,colour="black") + 
  facet_grid(chr ~ .)   + theme(axis.text.y = element_blank(),axis.ticks.y=element_blank(),legend.position="bottom") +
  theme(panel.background = element_rect(fill='white'), panel.grid.major = element_blank(), panel.grid.minor = element_blank())


ggplot(callable1k,aes(xmin=st,xmax=en,ymin=0,ymax=1)) + 
  ggtitle(paste("accessible regions (1kb windows)")) +
  geom_rect(aes(fill=accessible)) + scale_fill_manual(values=c("blue","orange","grey"))+
  geom_rect(data=chrlen, fill=NA,colour="black")+
  facet_grid(ch ~ .)  + blank_theme


```


```{r dev='postscript'}

ggplot(callable5k,aes(xmin=st,xmax=en,ymin=0,ymax=1)) + 
  ggtitle(paste("callable regions (5kb windows)")) +
  geom_rect(aes(fill=accessible,colour=accessible)) + scale_fill_manual(values=c("blue","orange","grey","#888888"))+ scale_colour_manual(values=c("blue","orange","grey","#888888"))+
  geom_rect(data=chrlen,fill=NA,colour="black") + 
  facet_grid(chr ~ .)   + theme(axis.text.y = element_blank(),axis.ticks.y=element_blank(),legend.position="bottom") +
  theme(panel.background = element_rect(fill='white'), panel.grid.major = element_blank(), panel.grid.minor = element_blank())

```
