library(ggplot2)
library(reshape2)
library(knitr)
```{r setup}
opts_chunk$set(fig.width=10, fig.height=9)

``` 

```{r}
reorder <- function(M,new_order) {
  M[lower.tri(M)] = t(M)[lower.tri(M)]
  M <- M[new_order,new_order]
  M[lower.tri(M)] <- NA
  M
}

sym <- function(M) {
  M[lower.tri(M)] = t(M)[lower.tri(M)]
  M
}


ggcolour <- function(n) {
  hues = seq(15, 375, length=n+1)
  hcl(h=hues, l=65, c=100)[1:n]
}


tree_order <- c(
"Th166.12", "Th246.13", "Th245.13", "Th211.13" ,"Th092.13" ,
"Th086.07", "Th106.09",  "Th230.12","Th074.13", "Th132.11","Th162.12","Th196.12", "Th106.11", "Th117.11", "Th134.11",
"Th068.12", "Th061.13", "Th095.13"
)
clades <- c(
  rep(2,5),
  rep(3,10),
  rep(1,3))
names(clades)<-tree_order
clades

```

```{r}

doubletons <- read.table("sharedDoubles_thies.txt",header=T,row.names=1,sep="\t")
total_dist <- read.table("Thies_manual.nj.dist.tab.txt",header=T,row.names=1,sep="\t")


doubletons <- reorder(doubletons,tree_order)
total_dist <- reorder(total_dist,tree_order)



```



```{r}

distances <- merge(
    melt(as.matrix(total_dist),value.name ="total",factorsAsStrings = T),
    melt(as.matrix(doubletons),value.name ="doubletons",factorsAsStrings = T),
    by=c("Var1","Var2")
    )
distances

#distances <- distances[distances$Var1!=distances$Var2,]
distances <- distances[!is.na(distances$total),]

distances$clade1 <- clades[distances$Var1]
distances$clade2 <- clades[distances$Var2]
distances$clades <- paste(clades[distances$Var1],clades[distances$Var2])

distances$interval_yrs <- abs(as.numeric(substr(as.character(distances$Var1),7,8)) - as.numeric(substr(as.character(distances$Var2),7,8)))
#distances$related <- distances$total < 10000
distances$related[distances$total >= 10000] <- "UNRELATED"
distances$related[distances$total < 10000] <- "RELATED"

distances$IBD <- distances$total < 2100


distances$Var1 <- factor(distances$Var1,levels=rev(tree_order))
distances$Var2 <- factor(distances$Var2,levels=rev(tree_order))


```

```{r}

relcol <- scale_color_manual(values=c("white","black"))
vxlab <- theme(axis.text.x = element_text(angle = 90, hjust = 1))  

ggplot(distances,aes(x=Var1,y=Var2,fill=total,label=total,colour=related)) + geom_tile() + scale_fill_gradient(trans="log") + geom_text(size=3) + relcol + vxlab
ggplot(distances,aes(x=Var1,y=Var2,fill=doubletons,label=doubletons,colour=doubletons)) + geom_tile() + scale_fill_gradient(trans="log") + geom_text(size=5) +  vxlab + scale_colour_gradient(low="white",high="red")


ggplot(distances,aes(x=total,y=doubletons,colour=related)) + geom_point() + scale_x_log10() + facet_grid(. ~ related)
ggplot(subset(distances,related=="RELATED"),aes(x=total,y=doubletons,colour=related)) + geom_point() + scale_x_log10() + facet_grid(. ~ related)
ggplot(subset(distances,related=="UNRELATED"),aes(x=total,y=doubletons,colour=related)) + geom_point() + scale_x_log10() + facet_grid(. ~ related)


```

```{r}

#total var distance vs indel ration

ggplot(distances,aes(x=total,y=ratio,colour=related)) + geom_point() + facet_grid(. ~ related,scale="free_x") + ylim(0,1.5)

#intervening years vs indel ratio
ggplot(distances,aes(x=interval_yrs,y=ratio,colour=related,label=clades)) + geom_text(size=4) +
  geom_smooth(aes(group=related,colour=related), method="lm",se=F) + facet_grid(. ~ related,scale="free_x") + ylim(0,1.5)

#intervening years vs total var distance
ggplot(distances,aes(x=interval_yrs,y=total,colour=total,group=related,label=clades)) + geom_text(size=4) +
  geom_smooth(aes(group=related,fill=related), method="lm",se=F)


ggplot(distances,aes(x=total,y=ratio,colour=total,group=related,label=clades)) + geom_text(size=4) +
  geom_smooth(aes(group=related,fill=related), method="lm",se=F) + ylim(0,1.3)


#SNP vs INDEL distances, all samples

ggplot(distances,aes(x=snp,y=indel,colour=related,group=related,label=clades)) + geom_text(size=4) + unrelatedLM + geom_abline(slope=0.5,linetype="dashed")
ggplot(subset(distances,related=="RELATED"),aes(x=snp,y=indel,colour=related,group=related,label=clades)) + geom_text(size=4) + unrelatedLM + geom_abline(linetype="dashed",slope=0.5)
ggplot(subset(distances,related=="UNRELATED"),aes(x=snp,y=indel,colour=related,group=related,label=clades)) + geom_text(size=4,colour=ggcolour(2)[[2]]) + unrelatedLM + geom_abline(linetype="dashed",slope=0.5)


#ggplot(distances,aes(x=snp,y=indel,colour=related,group=related,label=clades)) + geom_text(size=4) + unrelatedLM + facet_grid(. ~ related,scale="free")
#ggplot(subset(distances,related=="UNRELATED"),aes(x=snp,y=indel,colour=interval_yrs,group=related,label=clades)) + geom_text(size=4) + unrelatedLM
#ggplot(subset(distances,related=="RELATED"),aes(x=snp,y=indel,colour=interval_yrs,group=related,label=clades)) + geom_text(size=4) + unrelatedLM
#ggplot(subset(distances,related==F),aes(x=snp,y=indel,colour=total,group=related)) + geom_point(size=4)
```


