```{r}
library(ape)
library(adegenet)
library(phangorn)
library(knitr)
library(igraph)
library(RColorBrewer)
library(ggplot2)
library(reshape2)
library(outbreaker)
opts_chunk$set(fig.width=9, fig.height=9)
opts_chunk$set(dev=c('png'))
```




MRCA
```{r}

cl1 = c("Th196.12", "Th230.12", "Th132.11","Th162.12", "Th074.13", "Th106.09", "Th134.11", "Th117.11", "Th106.11","Th086.07")

ped <- read.table("Thies_all_manual.PASS.Cls.miss0.5.LMRG.HAP.ped",colClasses="character",na.strings = "0")
inds <- ped[,1]
ped <- ped[,seq(7,dim(ped)[[2]],2)]

genos <- apply(ped,2,function(x) {as.numeric(factor(x))})
genos[is.na(genos)] <- 0
rownames(genos)=inds

genosDat <- as.phyDat(genos, type="USER", levels = c(0:max(genos,na.rm=T),drop_null = F))
#genosDat <- as.phyDat(genos, type="USER", levels = c(0:5))

distmatH <- dist.hamming(genosDat)

discotree <- midpoint(nj(distmatH))
#discotree <- midpoint(njs(as.dist(sym(combDists))))

plot(discotree)
nodelabels()


#PARSIMONY ancestral state
ances.par <- ancestral.pars(discotree,genosDat)
#ML ancestral state 
fit = pml(discotree, genosDat)
ances.pml <- ancestral.pml(fit,type = "ml")
cl1mrca <- mrca.phylo(discotree,which(discotree$tip.label %in% cl1))
cl1mrca

#cl1mrca<-35
MLalleleMat <- ances.pml[[cl1mrca]]
maxLikelihoods <- apply(ances.pml[[cl1mrca]],1,FUN=max)
#MLallele <- matrix(as.numeric(MLallele),nrow = dim(MLallele)[1],dim(MLallele)[2])
MLallele <- rep(0,dim(MLalleleMat)[1])
for (i in c(0:dim(MLalleleMat)[2])) {
  MLallele[MLalleleMat[,i]==maxLikelihoods] <- i
}

genosDat$MRCA <- MLallele
genosM <- as.character(genosDat)
genosM[genosM==0]<-NA

```

discovar NJtree + MRCA
```{r}
genos <- apply(genosM,2,function(x) {as.numeric(factor(x))})
row.names(genos)<-row.names(genosM)
genosDat <- as.phyDat(genos[c(cl1,"MRCA"),], type="USER", levels = c(0:max(genos,na.rm=T),drop_null = F))
distmatH <- dist.hamming(genosDat)

discotree <- root(nj(distmatH),"MRCA")
```



```{r}
meta<-read.table("daniels.thies.CA.txt",sep="\t",header=T)
meta <- subset(meta,name %in% cl1)
rownames(meta) <- meta$name
cl1M <- c(as.character(meta$name),"MRCA")

for (MRCAyr in 2000:2008) {
  #MRCAyr <- MRCAyr+1
  cl1Y <- c(meta[as.character(meta$name),'year'],MRCAyr)
  cl1Ypos <- as.Date(paste("1","jan",cl1Y,sep=""),"%d%b%Y")
  names(cl1Ypos)<-cl1M
  
  cl1Mth <- (cl1Y-MRCAyr)*12
  names(cl1Mth)<-cl1M
  
  cl1N <- c(as.character(meta$name),"MRCA")
  
  
  
  # seqTrack(x = distmatM, x.names=cl1M, x.dates=cl1Ypos)
  distmatM <- as.matrix(distmatH)[cl1M,cl1M]
  strk <- seqTrack(distmatM, x.names=cl1M, x.dates=cl1Ypos)
  
  
  #cl1ob <- outbreaker(genosM[cl1M,],dates = cl1Y,w.dens = c(0.9,0.1,0.1,0.1,0.1,0.1),n.iter=1e4,init.tree = "random")
  
  genoSeg <- apply(genosM[cl1M,],2,FUN=function(x) {length(unique(na.omit(x)))>1})
  genoMAC <- apply(genosM[cl1M,],2,FUN=function(x) {min(table(na.omit(x)))})
  genoMAC[!genoSeg]<-0
  genoPars <- genoMAC>1
  
  itree <- strk$ances
  #itree[is.na(itree)]<-0
  sdec12mth <- c(0,seq(1,0.1,length.out = 11))
  expdec12mth <- c(0,1/10^seq(0,12))
  
  cl1ob <- outbreaker(genosM[cl1M,genoSeg],dates = cl1Mth,w.dens=expdec12mth,n.iter=5e4,init.tree = strk$ances)
  
  #transGraph(cl1ob, labels = cl1N,curved.edges = F,annot="support",main=paste("MRCA=",MRCAyr))
  plot(get.tTree(cl1ob),vertex.label=cl1N,main=paste("MRCA=",MRCAyr))
  plotOutbreak(cl1ob,xlim=c(0,(2015-MRCAyr)*12))
}
#plotChains(cl1ob )
# 
# 
# 
# barplot(cl1ob$w)
# 
# data(fakeOutbreak)
# fakeOutbreak$collecDates

```

