```{r}
library(ape)
library(adegenet)
library(phangorn)
library(knitr)
library(igraph)
library(RColorBrewer)
library(ggplot2)
library(reshape2)


#opts_chunk$set(fig.width=9, fig.height=9)
#opts_chunk$set(dev=c('png','postscript'))
opts_chunk$set(fig.width=12, fig.height=9)
opts_chunk$set(dev=c('png'))




```


```{r}
sym <- function(M) {
  M[lower.tri(M)] = t(M)[lower.tri(M)]
  M
}


makeDist <- function(distance_matrix_file, meta_file, ngroups=3) {
  mat <- read.table(distance_matrix_file,sep="\t")
  D <- as.dist(sym(mat))
  clust <- gengraph(D,ngrp=ngroups)
  names <- colnames(mat)
  mat <- as.matrix(mat)
  
  name1 <- names[clust$clust$membership==1]
  name2 <- names[clust$clust$membership==2]
  name3 <- names[clust$clust$membership==3]
  dist1 <- mat[name1,name1]
  dist2 <- mat[name2,name2]
  dist3 <- mat[name3,name3]
    
  list(dist1,dist2,dist3)
}

```

```{r}
meta <- read.table("Thies_metadata_1701.txt",sep="\t",header=T)
colnames(meta)[1]<-"name"
meta <- meta[!is.na(meta$Age),]

discoDists <- read.table("thies_disco.FILT.m0.5.dist.tab.txt",header=T,sep="\t")

meta <- subset(meta,name %in% names(discoDists))
rownames(meta) <- meta$name

hap100Dists <- read.table("thies_haplo100.FILT.m0.5.dist.tab.txt",header=T,sep="\t")

hap250Dists <- read.table("thies_haplo250.FILT.m0.5.dist.tab.txt",header=T,sep="\t")



samples <- read.table("Thies.samples.txt",col.names=c("ID","lane","dataset","sample","bam"))
samples <- unique(samples[,c("ID","sample")])
snames <- samples[,c("ID")]; samples<- as.character(samples[,c("sample")]) ; names(samples) <- snames

#fix names for hap100 tree
names(hap100Dists) <- samples[rownames(hap100Dists)]
rownames(hap100Dists) <- samples[rownames(hap100Dists)]


```




```{r }


makeNetSingle <- function(distance_matrix, meta) {
  if (class(distance_matrix)=="dist") {
    D = distance_matrix
    mat <- as.matrix(D)
  } else {
    mat <- read.table(distance_matrix,sep="\t")
    D <- as.dist(sym(mat))
    }
  
  names <- colnames(mat)
  mat <- as.matrix(mat)

  #limit meta to only these files
  rownames(meta) <- meta$name
  meta <- meta[names,]
  
  coll <- as.Date(as.character(meta$Date),"%d/%m/%Y",origin = "2000-01-01")
  #coll <- as.Date(paste("1","jan",meta$year,sep=""),"%d%b%Y")
  names(coll)<-meta$name
  meta$year <- as.numeric(format(coll,'%Y'))+2000

  
#   meta <- read.table("daniels.thies.CA.txt",sep="\t",header=T)
#   rownames(meta) <- meta$name
#   meta <- meta[names,]
#   coll <- as.Date(paste("1","jan",meta$year,sep=""),"%d%b%Y")
#   names(coll)<-meta$name

  year <- meta$year
  
  res <- seqTrack(mat, x.names=names, x.dates=coll)

  res$year <- year
  res$name <- names
  res
}



printGraph <- function(graph,colours,title) {
  cols <- brewer.pal((max(graph$year)-min(graph$year))+1, colours)

  ts=1 #textsize
  ig <- as.igraph(graph)
  tree <- layout_as_tree(ig,flip.y = F)[,c(2,1)]
  V(ig)$name <- graph$name
  V(ig)$color <- cols[graph$year-min(graph$year)+1]
  V(ig)$label.cex <- ts
 #frame()
  plot(ig,layout=tree,main=title,vertex.size=25,
     edge.color="black",edge.label.cex=1.5,edge.label.family="Arial",vertex.label.family="Arial")

}


getAnces <- function(net, leaf, ids=character()) {
    id = ids[1]
    ances = netAll[id,"ances"]
    date = netAll[id,"date"]
    ances.date = netAll[id,"ances.date"]
    #write(paste(leaf,id,ances,sep="\t"),stderr())
    if (!is.na(ances)) {
      if (id != leaf) {
        leaf.date = net[leaf,"date"]
        leaf.year = net[leaf,"year"]
        leaf.name = net[leaf,"name"]
        nextI = dim(net)[[1]]+1
#        write(paste("  adding",nextI,":",leaf,ances,sep=" "),stderr())
        net[nextI,1:2] <- c(leaf, ances)
        net[nextI,6] <- leaf.year
        net[nextI,7] <- leaf.name
        }
      net <- getAnces(net,leaf,c(ances))
    }
    if (length(ids) > 1){
       ids <- ids[ids != id]
#       write(paste("proceeding:",ids[1],sep=" "),stderr())
       net <- getAnces(net,ids[1],ids)
  }
net
}

getEvolRates <- function(net,mat,ng) {
  netAll <- getAnces(net, net$id[1],net$id)
  
  D <- as.dist(sym(mat))
  names <- colnames(mat)
  mat <- as.matrix(sym(mat))
  outgroups <- setdiff(names,net$name)
  
  outtab <- data.frame(from=character(),
                 to=character(),
                 out=character(),
                 time=integer(),
                 distance=numeric(),
                 rate=numeric(),
                 stringsAsFactors=FALSE)
  
  for (i in c(1:dim(netAll)[[1]])) {
    if(!is.na(netAll$ances[i])) {
      sample = netAll$name[i]
      ances = netAll$name[netAll$ances[i]]
      dists = c()
      
      time <- as.integer(netAll$year[i] - netAll$year[netAll$ances[i]])
      
      for (o in outgroups) {
        dist <- mat[sample,o]-mat[ances,o]
        dists <- c(dists, dist)
        outtab[dim(outtab)[1]+1,1:3]=c(ances,sample,o)
        outtab[dim(outtab)[1],4:6]=c(time,dist,round(dist/time,2))        
      }
      dists <- round(dists/time)
      #paste(dists,collapse = ","),
#      write(paste(ances,sample,time,round(mean(dists),2),round(sd(dists),2),sep="\t"),stdout())
#      write(paste(ances,sample,outgroups,time,dists,sep="\t"),stdout())
    }
  }
  outtab$pair <- paste(outtab$from,outtab$to)
  outtab
}



g_legend<-function(a.gplot){
  tmp <- ggplot_gtable(ggplot_build(a.gplot))
  leg <- which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend <- tmp$grobs[[leg]]
  return(legend)}
```


```{r}
cl1 <- c("Th086.07", "Th106.09", "Th106.11", "Th117.11", "Th132.11", "Th134.11", "Th162.12", "Th196.12", "Th230.12", "Th074.13")
cl1yrs <- as.numeric(gsub(".*\\.","",cl1))
og1<-"Th166.12"
oc1 <- c("Th166.12", "Th092.13", "Th211.13", "Th245.13", "Th246.13")
og2<-"Th068.12"
oc2 <- c("Th068.12", "Th061.13", "Th095.13")
cog1 <- c(cl1,og1)
cog2 <- c(cl1,og2)


```



```{r}
discoNJtree <- nj(as.dist(sym(discoDists)))
discoNJtree <- midpoint(discoNJtree)
plot(discoNJtree)
discoNJtree <- drop.tip(discoNJtree,c(oc1,oc2))
plot(discoNJtree)

discoRTdist <- diag(vcv.phylo(discoNJtree)[cl1,cl1])
discoMEPtab <- data.frame("sample"=cl1,"yrs"=cl1yrs,"rtdist"=discoRTdist)
ct1 <- cor.test(discoMEPtab$yrs,discoMEPtab$rtdist)
ct1
ggplot(discoMEPtab,aes(x=yrs,y=rtdist,label=sample)) + geom_text(size=4) + geom_smooth(method = lm,se=F,linetype=2) + 
  geom_label(x=8,y=mean(TDtab1$rtdist),label=paste("R=",round(ct1$estimate,3)," p=",round(ct1$p.value,4),sep=""),size=5) +
  ggtitle("Discovar, distance-time correlation extended genome")

```


```{r}
hap100NJtree <- nj(as.dist(sym(hap100Dists)))
hap100NJtree <- midpoint(hap100NJtree)
plot(hap100NJtree)
hap100NJtree <- drop.tip(hap100NJtree,c(oc1,oc2))
plot(hap100NJtree)

hap100RTdist <- diag(vcv.phylo(hap100NJtree)[cl1,cl1])
hap100MEPtab <- data.frame("sample"=cl1,"yrs"=cl1yrs,"rtdist"=hap100RTdist)
ct1 <- cor.test(hap100MEPtab$yrs,hap100MEPtab$rtdist)
ct1
ggplot(hap100MEPtab,aes(x=yrs,y=rtdist,label=sample)) + geom_text(size=4) + geom_smooth(method = lm,se=F,linetype=2) + 
  geom_label(x=8,y=mean(TDtab1$rtdist),label=paste("R=",round(ct1$estimate,3)," p=",round(ct1$p.value,4),sep=""),size=5) +
  ggtitle("hap100, distance-time correlation extended genome")

```


```{r}
hap250NJtree <- nj(as.dist(sym(hap250Dists)))
hap250NJtree <- midpoint(hap250NJtree)
plot(hap250NJtree)
hap250NJtree <- drop.tip(hap250NJtree,c(oc1,oc2))
plot(hap250NJtree)

hap250RTdist <- diag(vcv.phylo(hap250NJtree)[cl1,cl1])
hap250MEPtab <- data.frame("sample"=cl1,"yrs"=cl1yrs,"rtdist"=hap250RTdist)
ct1 <- cor.test(hap250MEPtab$yrs,hap250MEPtab$rtdist)
ct1
ggplot(hap250MEPtab,aes(x=yrs,y=rtdist,label=sample)) + geom_text(size=4) + geom_smooth(method = lm,se=F,linetype=2) + 
  geom_label(x=8,y=mean(TDtab1$rtdist),label=paste("R=",round(ct1$estimate,3)," p=",round(ct1$p.value,4),sep=""),size=5) +
  ggtitle("hap250, distance-time correlation extended genome")

```

```{r}
discoMEPtab$prog <- "disco"
hap100MEPtab$prog <- "haplo100"
hap250MEPtab$prog <- "haplo250"
cfMEPtab<-rbind(discoMEPtab,hap100MEPtab,hap250MEPtab)

ggplot(cfMEPtab,aes(x=yrs,y=rtdist,label=sample)) + geom_text(size=4) + geom_smooth(method = lm,se=F,linetype=2) + 
  geom_label(x=8,y=mean(TDtab1$rtdist),label=paste("R=",round(ct1$estimate,3)," p=",round(ct1$p.value,4),sep=""),size=5) + facet_grid(. ~ prog) + 
  ggtitle("hap250, distance-time correlation extended genome")


```



```{r}

netDisco <- makeNetSingle(as.dist(sym(discoDists[cl1,cl1])),meta)
printGraph(netDisco,"Greens",title = "Discovar - clade29")

```


```{r}
netHap100 <- makeNetSingle(as.dist(sym(hap100Dists)[cl1,cl1]),meta)
printGraph(netHap100,"Greens",title = "Haplo100 - clade29")

```

```{r}
netHap250 <- makeNetSingle(as.dist(sym(hap250Dists)[cl1,cl1]),meta)
printGraph(netHap250,"Greens",title = "Haplo250 - clade29")

```



```{r}

bootstrapNets <- function(genos,outfolder) {
  genosStatic <- genos
  #outfolder <- "./bootstraps"
  bstraps <- system(paste("ls ",outfolder,"*",sep=""),intern = T)
  if (length(bstraps)>0) {write("using old bootstraps",stderr())
  #if (1==2) {write("using old bootstraps",stderr())
                       } else{
    write("bootstrapping (100)",stderr())
      for (boot in c(1:100)) {
      
          bootsample <- sample(c(1:dim(genos)[1]),replace = T)
#          genos <- genosStatic[c1,bootsample]
#          inds <- c1
          genos <- genosStatic[bootsample,]
          inds <- colnames(genosStatic)
        
          distmat = matrix(nrow=length(inds),ncol=length(inds))
          colnames(distmat) = inds
          rownames(distmat) = inds
        
          write("calculating distance matrix",stderr())
          for (i in inds){
              for (j in inds){
#              filled = intersect(which(genos[,i] != 0), which(genos[,j] !=0))
              filled = intersect(which(!is.na(genos[,i])), which(!is.na(genos[,j])))
              if(length(filled) > 0) {
                  distmat[j,i] = sum(genos[filled,i]!=genos[filled,j])
                }else {
                  distmat[j,i]=-1
                }
              }
          }
          distmat <- as.dist(distmat)
          net <- makeNetSingle(distmat,meta)
          #printGraph(net,"Greens",tab)
          
          outnet=paste(".",outfolder, paste("bootstrap_c29",boot,'seqtrack.net',sep='.'),sep="/")
          write.table(net,outnet,quote=F,row.names=F)
        
        }
  }
}

sumBootstraps <- function(bootdir) {
  bstraps <- system(paste("ls ",bootdir,"/*",sep=""),intern = T)

  blinks <- matrix(rep(0,length(cl1)**2),nrow = length(cl1),ncol=length(cl1),dimnames = list(cl1,cl1))

  for (b in bstraps) {
    tab <- read.table(b,header=T)
    for (i in c(1:dim(tab)[[1]])) {
      if (!is.na(tab$ances[i])) {
      blinks[tab$id[i],tab$ances[i]] = blinks[tab$id[i],tab$ances[i]]+1
      }
    }
  }
blinks
}

```

```{r}

discoGenos <- read.table("thies_disco.FILT.m0.5.alleles.tab",header=T,na.strings = c("."))[,cl1]
bootstrapNets(discoGenos,"bootstraps_disco")
discosum <- sumBootstraps("bootstraps_disco")

hap100Genos <- read.table("thies_haplo100.FILT.m0.5.alleles.tab",header=T,na.strings = c("."))
cnames <- gsub("SM.","SM-",colnames(hap100Genos))
cnames[cnames %in% names(samples)] <- samples[cnames[cnames %in% names(samples)]]
colnames(hap100Genos) <- cnames
hap100Genos <- hap100Genos[,cl1]
bootstrapNets(hap100Genos,"bootstraps_hap100")
hap100sum <- sumBootstraps("bootstraps_hap100")



hap250Genos <- read.table("thies_haplo250.FILT.m0.5.alleles.tab",header=T,na.strings = c("."))[,cl1]
bootstrapNets(hap250Genos,"bootstraps_hap250")
hap250sum <- sumBootstraps("bootstraps_hap250")

```


```{r}
addBootToNet <- function(net,boottab,distmat) {
  net$type = "core"
  net$boot = 0
  inds <- rownames(net)
  for (t in inds) {
    for (f in inds) {
      fi = which(inds==f)
        #write(paste(t,f,blinks[t,f],net[t,"ances"],is.na(net[t,"ances"]),net[t,"ances"] == fi),stderr())
      if (boottab[t,f] > 0) {
        if ((!is.na(net[t,"ances"])) & net[t,"ances"] == fi) {net[t,"boot"] = boottab[t,f]}
        else {
          nextI = dim(net)[[1]]+1
  #        write(paste("  adding",nextI,":",leaf,ances,sep=" "),stderr())
          #integers
          net[nextI,c("id","ances","weight","year","boot")] <- c(which(inds==t), which(inds==f),as.matrix(distmat)[t,f],net[t,"year"], boottab[t,f])
          net[nextI,4] <- meta[f,"Date"]
          net[nextI,5] <- net[t,"date"]
          net[nextI,7:8] <- c(t,"boot")
          }
        }
    }
  }
net
}

discobootnet <- addBootToNet(netDisco,discosum,discoDists)
hap100bootnet <- addBootToNet(netHap100,hap100sum,hap100Dists)
hap250bootnet <- addBootToNet(netHap250,hap250sum,hap250Dists)
discobootnet
hap100bootnet
hap250bootnet



```