#!/bin/bash

echo "parseDone.pl"
perl parseDone.pl 3D7DD2/sub_commands.out.log
rc=$?
if [[ $rc != 0 ]]; then
 echo "could not parse done jobs"
 exit $rc
fi

echo "getting sample-regions"
cat 3D7DD2/done_commands.15* | sort -u > 3D7DD2/done_commands.cat.txt
cut -d\  -f 10-12 3D7DD2/done_commands.cat.txt > done_sample_region.txt

echo "getCompletedRegions.py"
python $DISCO1/pipeline/getCompletedRegions.py \
       -f $WORK/refs/Pf3D7_v3.fasta \
       -s $DISCO1/samples/3D7DD2.samples.txt \
       -F ./done_sample_region.txt



#rm 3D7DD2/sub_commands.out.log
