library(ggplot2)
library(knitr)
library(reshape2)
library(hexbin)
```{r setup}
opts_chunk$set(fig.width=12, fig.height=7)

# matchlevels <- c("",     "NUCMER","DISCO","HAPLO","NUCMER,DISCO","NUCMER,HAPLO","DISCO,HAPLO","NUCMER,DISCO,HAPLO")
# colours <-     c("black","green", "red",  "blue", "yellow",      "cyan",        "magenta",     "white")
# names(colours) <- matchlevels

``` 

```{r}
#vartypes <- read.table("pfx_v_3D7DD2fullrun_miss0callable.PASS.DD2CONC.R3.varClass.txt",stringsAsFactors = F,sep='\t',header=T)
vartypes <- read.table("pfx_v_3D7DD2fullrun_miss0callable.PASS.DD2CONC.VARCLASS.varClass.txt",stringsAsFactors = F,sep='\t',header=T)
#3D7 only:
vartypes$refsAbsent = vartypes$FDKRefAbsent
vartypes$anyDiscord = vartypes$X2D4Discord | vartypes$FDKDiscord | vartypes$FDK2D4Incons
vartypes$anyDiscord <- as.numeric(vartypes$anyDiscord)
vartypes$abslen = abs(vartypes$varlen)

vartypes$STR = 0
vartypes$STR[vartypes$STRtype != ""] <- 1

vartypes$coding[vartypes$coding=="intergenic"] <- 0
vartypes$coding[vartypes$coding=="coding"] <- 1
#head(vartypes$coding,50)
vartypes$coding <- as.numeric(vartypes$coding)
#head(vartypes$coding,50)


#set max call length to read length (only one above this)
#vartypes <- subset(vartypes,abslen < 500)
vartypes$maxcons = vartypes$consequence
vartypes$maxcons[vartypes$consequence==""] <- "intergenic"
vartypes$maxcons <- unlist(lapply(vartypes$maxcons,FUN=function(x) {unlist(strsplit(x,split ='&'))[[1]]}))

vartypes$effect="NONE"
vartypes$effect[vartypes$maxcons %in% c("frameshift_variant","stop_lost","start_lost","stop_gained","exon_loss_variant")] <- "NONSENSE"
vartypes$effect[vartypes$maxcons %in% c("missense_variant","disruptive_inframe_insertion","disruptive_inframe_deletion","splice_region_variant")] <- "MISSENSE"
vartypes$effect[vartypes$maxcons %in% c("inframe_insertion","inframe_deletion","synonymous_variant","intergenic","intragenic_variant","non_coding_exon_variant")] <- "NEUTRAL"

                           

indels <- subset(vartypes,vartype=="INDEL")
snps <- subset(vartypes,vartype=="SNP")
```

```{r}
# #subset(vartypes,anyDiscord)
# #summary(indels[,c("STR","DUST","coding","anyDiscord","effect")])
# colMeans(indels[,c("STR","DUST","coding","anyDiscord")])
# #no appreciable drop in discordance with STRs
# colMeans(subset(indels,STR==1)[,c("STR","DUST","coding","anyDiscord")])
# colMeans(subset(indels,STRtype=="STR")[,c("STR","DUST","coding","anyDiscord")])
# colMeans(subset(indels,STRtype=="polyA")[,c("STR","DUST","coding","anyDiscord")])
# colMeans(subset(indels,STRtype=="TArich")[,c("STR","DUST","coding","anyDiscord")])
# #large increase in discordance with TA-repeats
# colMeans(subset(indels,STRtype=="TArep")[,c("STR","DUST","coding","anyDiscord")])
# 
# colMeans(subset(snps,STR==1)[,c("STR","DUST","coding","anyDiscord")])
# colMeans(subset(snps,STRtype=="STR")[,c("STR","DUST","coding","anyDiscord")])
# colMeans(subset(snps,STRtype=="polyA")[,c("STR","DUST","coding","anyDiscord")])
# colMeans(subset(snps,STRtype=="TArich")[,c("STR","DUST","coding","anyDiscord")])
# colMeans(subset(snps,STRtype=="TArep")[,c("STR","DUST","coding","anyDiscord")])

```

#INDEL SIZE DISTRIBUTION
```{r}

#indels are longer in STRs
ggplot(indels,aes(x=abslen,colour=STRtype,group=STRtype)) + 
  ggtitle(paste("indel length by STR presence / type")) +
  geom_density(size=1,alpha=0.7) +
  xlim(0,50)

#SOME V LONG INDELS
indels[indels$abslen > 50,c("chr","pos","vartype","STRtype","varlen","coding","consequence")]
ggplot(indels[indels$abslen > 50,],aes(x=abslen,y=vcomplex,colour=STRtype)) + 
  ggtitle(paste("long indels: length v complexity")) +
  xlim(50,400) +
  geom_point(size=3,alpha=1)
ggplot(indels[indels$abslen > 50,],aes(x=abslen,y=vcomplex,colour=STRtype)) + 
  ggtitle(paste("long indels: length v complexity")) +
  xlim(1600,2000) +
  geom_point(size=3,alpha=1)

#RELATIVELY SMALL NUMBER ARE TA REPEATS (possible difficulties in calling really long TA repeats?)
ggplot(indels[indels$abslen > 50,],aes(x=abslen,y=vcomplex,colour=consequence)) + 
  ggtitle(paste("long indels: coding consequences")) +
  xlim(50,400) +theme(legend.position="bottom")+guides(col = guide_legend(nrow = 2))+
  geom_point(size=3,alpha=1)

#RELATIVELY SMALL NUMBER OF CODING SNPs ARE polyA REPEATS (possible difficulties in calling really long TA repeats?)
table(indels[,c("maxcons","STRtype")])

#RELATIVELY SMALL NUMBER OF CODING SNPs ARE polyA REPEATS (possible difficulties in calling really long TA repeats?)
table(indels[,c("maxcons","INDtype")])

```

#tables of STR types and discordance
```{r}

#aggregate(anyDiscord ~ STRtype + vartype, data=vartypes,FUN = mean)
#aggregate(anyDiscord ~ STRtype + vartype, data=vartypes,FUN = sum)

#where TA-repeats can be called, may have much higher freqs of discordance?
cbind(aggregate(anyDiscord ~ STRtype + vartype, data=vartypes,FUN = function(x) {sum(!is.na(x))})[,1:2],
      "n"=aggregate(anyDiscord ~ STRtype + vartype, data=vartypes,FUN = function(x) {sum(!is.na(x))})[,3],
      "discord"=aggregate(anyDiscord ~ STRtype + vartype, data=vartypes,FUN = sum)[,3],
      "discord_f"=round(aggregate(anyDiscord ~ STRtype + vartype, data=vartypes,FUN = mean)[,"anyDiscord"],3))

#vast majority of discordant mutations are TA repeat INDELS
cbind(aggregate(anyDiscord ~ INDtype + vartype, data=vartypes,FUN = function(x) {sum(!is.na(x))})[,1:2],
      "n"=aggregate(anyDiscord ~ INDtype + vartype, data=vartypes,FUN = function(x) {sum(!is.na(x))})[,3],
      "discord"=aggregate(anyDiscord ~ INDtype + vartype, data=vartypes,FUN = sum)[,3],
      "discord_f"=round(aggregate(anyDiscord ~ INDtype + vartype, data=vartypes,FUN = mean)[,"anyDiscord"],3))

#most discordant loci in indels, over half in low-complexity regions
cbind(aggregate(anyDiscord ~ DUST + vartype, data=vartypes,FUN = function(x) {sum(!is.na(x))})[,1:2],
      "n"=aggregate(anyDiscord ~ DUST + vartype, data=vartypes,FUN = function(x) {sum(!is.na(x))})[,3],
      "discord"=aggregate(anyDiscord ~ DUST + vartype, data=vartypes,FUN = sum)[,3],
      "discord_f"=round(aggregate(anyDiscord ~ DUST + vartype, data=vartypes,FUN = mean)[,"anyDiscord"],3))


```


```{r, fig.width=10,fig.height7}


#most indels intergenic or neutral
ggplot(vartypes,aes(x=effect,fill=maxcons,group=maxcons)) + 
  ggtitle(paste("consequence v var type")) +
  geom_bar() + facet_grid(. ~ vartype, scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))
```

```{r,fig.width=10,fig.height=12}

#TA rich STRs more likely to generate missense/nonsense mutations?
ggplot(vartypes,aes(x=effect,fill=maxcons,group=maxcons)) + 
  ggtitle(paste("consequence v STR type")) +
  geom_bar() + facet_grid(STRtype ~ vartype, scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))

ggplot(subset(vartypes,coding==1),aes(x=effect,fill=maxcons,group=maxcons)) + 
  ggtitle(paste("consequence v STR type (coding only)")) +
  geom_bar() + facet_grid(STRtype ~ vartype, scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))

```


##TA-RICH INDELS MORE LIKELY TO CAUSE CODING CHANGES?
```{r, fig.width=7,fig.height=12}

#most indels intergenic or neutral
#TA rich STRs more likely to generate missense/nonsense mutations?
ggplot(indels,aes(x=effect,fill=maxcons,group=maxcons)) + 
  ggtitle(paste("consequence v INDEL type")) +
  geom_bar() + facet_grid(INDtype ~ ., scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))

#MOST CODING DIFFS ARE POLY-A INSERTIONS
ggplot(subset(indels,coding==1),aes(x=effect,fill=maxcons,group=maxcons)) + 
  ggtitle(paste("consequence v INDEL type (coding only)")) +
  geom_bar() + facet_grid(INDtype ~ ., scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))

```

##VAST MAJORITY OF TA/polyA in intergenic sequence
```{r,fig.width=10,fig.height=7}
ggplot(indels,aes(x=effect,fill=INDtype,group=INDtype)) + 
  ggtitle(paste("consequence v INDEL type")) +
  geom_bar() + facet_grid(. ~ coding, scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))
```

##NO MORE LIKELY TO BE DISCORDANT
```{r,fig.width=10,fig.height=10}
# ggplot(indels,aes(x=effect,fill=INDtype,group=INDtype)) + 
#   ggtitle(paste("consequence v INDEL type")) +
#   geom_bar() + facet_grid(anyDiscord ~ coding, scale="free_y") + 
#   theme(axis.text.x=element_text(angle=-90,size=14))

#NO MAJOR DIFFERENCES IN RATIOS FOR CONCORDANT/DISCORDANT VARS
ggplot(subset(indels),aes(x=effect,fill=maxcons,group=maxcons)) + 
  ggtitle(paste("consequence v concordance (all)")) +
  geom_bar() + facet_grid(anyDiscord ~ ., scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))

ggplot(subset(indels,coding==1),aes(x=effect,fill=maxcons,group=maxcons)) + 
  ggtitle(paste("consequence v concordance (coding)")) +
  geom_bar() + facet_grid(anyDiscord ~ ., scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))

```

```{r, fig.width=10, fig.height=7}

#NO MAJOR DIFFERENCES IN RATIOS FOR LOW-COMPLEXITY SEQ
ggplot(subset(indels),aes(x=effect,fill=maxcons,group=maxcons)) + 
  ggtitle(paste("consequence v concordance (all)")) +
  geom_bar() + facet_grid(DUST ~ ., scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))

#NO MAJOR DIFFERENCES IN RATIOS FOR LOW-COMPLEXITY SEQ
ggplot(subset(indels,coding==1),aes(x=effect,fill=maxcons,group=maxcons)) + 
  ggtitle(paste("consequence v concordance (all)")) +
  geom_bar() + facet_grid(DUST ~ ., scale="free_y") + 
  theme(axis.text.x=element_text(angle=-90,size=14))

```

